// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	LoginName string `json:"loginName"`
	Password  string `json:"password"`
}

type LoginResponse struct {
	Id    uint64 `json:"id"`
	Token string `json:"token"`
}

type RegisterRequest struct {
	LoginName string `json:"loginName"`
	UserName  string `json:"userName"`
	PassWord  string `json:"passWord"`
	Sex       uint64 `json:"sex"`
}

type RegisterResponse struct {
}

type UserInfoRequest struct {
	Id uint64 `json:"id"`
}

type UserInfoResponse struct {
	Id        uint64 `json:"id"`
	UserName  string `json:"userName"`
	LoginName string `json:"loginName"`
	Sex       uint64 `json:"sex"`
}
