// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `form:"name"`
	Password string `form:"password"`
}

type LoginResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}
